version: "2"
services:
  web:
    build: .
    ports:
      - "80:3000"
    environment:
      SOLVER_DOMAIN_NAME: solver
  solver:
    build: ./sudoku_server
    domainname: solver
    expose:
      - "5000"
